### ISSUE TITLE
Cannot open files

### ISSUE THREAD

**Issue by oierbanos** [CriticalPathSecurity/Zeek-Intelligence-Feeds#24]
Hi!

When I use the feeds I get this error:

`1495094790.731429 warning: /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/cps_cobaltstrike_ip.intel/Input::READER_ASCII: Init: cannot open /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/cps_cobaltstrike_ip.intel
1495094790.731429 warning: /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/cps_cobaltstrike_domain.intel/Input::READER_ASCII: Init: cannot open /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/cps_cobaltstrike_domain.intel
1495094790.731429 warning: /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/dom-bl.intel/Input::READER_ASCII: Init: cannot open /usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/dom-bl.intel`

The first two files don't exist, but I also don't see them on main.zeek

Apart from that, I don't see these files on main.zeek:

- abuse-ja3-fingerprints.intel
- atomspam.intel
- censys.intel
- cobaltstrike_ips.intel
- filetransferportals.intel
- illuminate_ja3.intel (I remember posting an issue that was related to illuminate so maybe this file is not present for a reason)
- lockbit_ip.intel
- ragnar.intel
- rdpsnitch.intel
- salesforce-ja3-fingerprints.intel

Are these files not present for a reason? I prefer to ask just in case.

Thank you!!

**Comment by Patrick-Kelley** [comment]
Investigating and resolving, immediately! 

Thank you for the notification.

**Comment by oierbanos** [comment]
Hi again!

Now I found that `Cyber_Threat_Coalition_Domain_Blacklist.intel` is empty...

**Comment by Patrick-Kelley** [comment]
The first two you mentioned are indeed, removed. They were rolled into a cleaner and more quickly updated feed. 

I try to make adjustments such as removing a feed as sparingly as possible. 

I'm adjusting the main.zeek to account for the missing feeds. The Cyber_Threat_Coalition_Domain_Blacklist.intel is empty as the COVID-19 CTI League has stopped producing a feed. It is still listed as it is my hope to build a feed from the intelligence gathered from the Slack channels. Due to the TLP assignments, this might take a bit longer.

**Comment by oierbanos** [comment]
Great, thank you, @Patrick-Kelley!

**Comment by Patrick-Kelley** [comment]
<img width="586" alt="Screenshot 2023-03-07 at 12 49 10 PM" src="https://user-images.githubusercontent.com/5044195/223506439-0b668ab9-2730-47ed-b03f-a9548c89388e.png">

I believe the issues have been resolved. Does it look that way on your end?

**Comment by oierbanos** [comment]
I still get the same warnings, but now that I know that those are files that have been deleted, I will just ignore them.

main.zeek looks ok to me.

The only strange thing I see is this: `1601484518.419370 warning: Value 'Intel:::EMAIL' for stream 'intel-/usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds/cps-collected-iocs.intel' is not a valid enum.
`
Probably a typo, because there are three colons in "Intel:::EMAIL"

**Comment by Patrick-Kelley** [comment]
<img width="509" alt="Screenshot 2023-03-08 at 8 07 13 AM" src="https://user-images.githubusercontent.com/5044195/223721418-586cb561-210b-4a1c-a061-4e2f97f2dd32.png">
<img width="888" alt="Screenshot 2023-03-08 at 8 07 55 AM" src="https://user-images.githubusercontent.com/5044195/223721445-1597cc7e-6130-4e13-8b45-e397b35405c7.png">

I corrected the offending line. 

Also, a bit of back story... The linter warns on anything that might not work. Unfortunately, there are a bunch of malware and ransomware URLs that work in the product, but break in the linter. 

I'll improve the linter in the coming weeks and that should resolve it.
